### ISSUE TITLE
Mailbox Bug?

### ISSUE THREAD

**Issue by thedarkcookieez** [TRCStudioDean/GlobalMarketPlus#2]
`[17:50:26 ERROR]: Could not pass event InventoryClickEvent to GlobalMarketPlus v1.0.3.11
org.bukkit.command.CommandException: Unhandled exception executing command 'gmp' in plugin GlobalMarketPlus v1.0.3.11
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916) ~[paper-1.19.2.jar:git-Paper-296]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:718) ~[paper-1.19.2.jar:git-Paper-296]
        at studio.trc.bukkit.globalmarketplus.m.a.e.a(Unknown Source) ~[GlobalMarketPlus-1.0.3.11.jar:?]
        at studio.trc.bukkit.globalmarketplus.m.a.h.a(Unknown Source) ~[GlobalMarketPlus-1.0.3.11.jar:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at studio.trc.bukkit.globalmarketplus.m.a.h.a(Unknown Source) ~[GlobalMarketPlus-1.0.3.11.jar:?]
        at studio.trc.bukkit.globalmarketplus.e.m.a.b.a(Unknown Source) ~[GlobalMarketPlus-1.0.3.11.jar:?]
        at studio.trc.bukkit.globalmarketplus.e.m.a.a(Unknown Source) ~[GlobalMarketPlus-1.0.3.11.jar:?]
        at studio.trc.bukkit.globalmarketplus.d.a.a(Unknown Source) ~[GlobalMarketPlus-1.0.3.11.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor48.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-296]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3307) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-296]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-296]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-296]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-296]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-296]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.2.jar:git-Paper-296]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.2.jar:git-Paper-296]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-296]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
        at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
        at studio.trc.bukkit.globalmarketplus.a.a.k.a(Unknown Source) ~[GlobalMarketPlus-1.0.3.11.jar:?]
        at studio.trc.bukkit.globalmarketplus.l.c.a(Unknown Source) ~[GlobalMarketPlus-1.0.3.11.jar:?]
        at studio.trc.bukkit.globalmarketplus.a.a.k.e(Unknown Source) ~[GlobalMarketPlus-1.0.3.11.jar:?]
        at studio.trc.bukkit.globalmarketplus.a.a.k.a(Unknown Source) ~[GlobalMarketPlus-1.0.3.11.jar:?]
        at studio.trc.bukkit.globalmarketplus.a.a.a(Unknown Source) ~[GlobalMarketPlus-1.0.3.11.jar:?]
        at studio.trc.bukkit.globalmarketplus.a.a.onCommand(Unknown Source) ~[GlobalMarketPlus-1.0.3.11.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 33 `

I was told ingame that I had something in my mailbox but the items were not displayed

**Comment by TRCStudioDean** [comment]
Try to update to latest version

**Comment by thedarkcookieez** [comment]
Version Update
